#!/bin/bash

# We have to be careful when editing the sudoers file. Syntax errors cause problems!
#STRING="ALL	ALL=(root) NOPASSWD: /usr/bin/killall -9 loginwindow"
REBOOT="ALL	ALL=(root) NOPASSWD: /sbin/reboot -q"
FVREBOOT="ALL	ALL=(root) NOPASSWD: /usr/bin/fdesetup authrestart"
SHUTDOWN="ALL	ALL=(root) NOPASSWD: /sbin/shutdown -h now"

if $(grep -q "$REBOOT" /etc/sudoers) && $(grep -q "$SHUTDOWN" /etc/sudoers) && $(grep -q "$FVREBOOT" /etc/sudoers); then
	# Nothing to be done
	exit 0
fi

# Make a working copy
cp /etc/sudoers /tmp/sudoers.tmp
# Echo in our changes
echo "$REBOOT" >> /tmp/sudoers.tmp
echo "$FVREBOOT" >> /tmp/sudoers.tmp
echo "$SHUTDOWN" >> /tmp/sudoers.tmp

# Validate the changes
visudo -cqsf /tmp/sudoers.tmp

# visudo exits 0 if the changes are syntactically correct
if [[ $? -eq 0 ]]; then
	cp /tmp/sudoers.tmp /etc/sudoers
fi

exit 0
