#!/bin/bash

# We have to be careful when editing the sudoers file. Syntax errors cause problems!
#STRING="ALL	ALL=(root) NOPASSWD: /usr/bin/killall -9 loginwindow"
STRING="ALL	ALL=(root) NOPASSWD: /sbin/reboot -q"

if $(grep -q "$STRING" /etc/sudoers); then
	# Nothing to be done
	exit 0
fi

# Make a working copy
cp /etc/sudoers /tmp/sudoers.tmp
# Echo in our changes
echo "$STRING" >> /tmp/sudoers.tmp

# Validate the changes
visudo -cqsf /tmp/sudoers.tmp

# visudo exits 0 if the changes are syntactically correct
if [[ $? -eq 0 ]]; then
	cp /tmp/sudoers.tmp /etc/sudoers
fi

exit 0
